platform :ios, '10.0'

target 'keyboard' do
  pod 'Masonry'
  pod 'NSAttributedString-DDHTML'
end

target 'remotekb' do
  pod 'Masonry'
  pod 'Toast'
  pod 'SCLAlertView-Objective-C'
  pod 'AppCenter'

end
